In [3]:
f = "/Users/seonils/dev/rims_minimal/src/0_refactoring/dbg_llama/check/processed_indiv._inspect.jsonl"
import pandas as pd
df = pd.read_json(f, lines=True)

In [4]:
# check majvote_answers and need_selection
df
# ignore submission column as it is overwritten by every evaluation of cot pal and p2c (so it is the submission of p2c)

,question,cot_solutions,pal_solutions,p2c_solutions,cot_preds,pal_preds,p2c_preds,majvote_answers,need_selection,answer,submission,cot,pal,p2c
0,Janet’s ducks lay 16 eggs per day. She eats th...,[Answer:\nJanet's ducks lay 16 eggs per day.\n...,"[def solution():\n """"""Janet’s ducks lay 16 ...",[def solution():\n '''\n Create a functi...,[18.0],[18.0],[18.0],[18.0],[False],18,18.0,True,1.0,1.0
1,A robe takes 2 bolts of blue fiber and half th...,[Answer:\nThe robe takes 2 bolts of blue fiber...,"[def solution():\n """"""A robe takes 2 bolts ...",[def solution():\n '''\n Create a functi...,[3.0],[3.0],[4.0],[3.0],[False],3,4.0,True,1.0,0.0
2,Josh decides to try flipping a house. He buys...,"[Answer:\nJosh bought the house for $80,000.\n...","[def solution():\n """"""Josh decides to try f...",[Here is the Python function that solves the p...,[10000.0],[325000.0],[None],[None],[True],70000,None,False,0.0,NaN
3,James decides to run 3 sprints 3 times a week....,[Answer:\nJames runs 3 sprints 3 times a week....,"[def solution():\n """"""James decides to run ...",[def solution():\n '''\n Create a functi...,[540.0],[540.0],[540.0],[540.0],[False],540,540.0,True,1.0,1.0
4,"Every day, Wendi feeds each of her chickens th...",[Answer:\nWendi gives her chickens 15 cups of ...,"[def solution():\n """"""Every day, Wendi feed...",[def solution():\n '''\n Create a functi...,[20.0],[60.0],[20.0],[20.0],[False],20,20.0,True,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1314,John had a son James when he was 19. James is...,"[Answer:\nJohn had James when he was 19, so Ja...","[def solution():\n """"""John had a son James ...",[Here is the solution:\n\n],[16.0],[3.0],[None],[None],[True],8,None,False,0.0,NaN
1315,There are some oranges in a basket. Ana spends...,"[Answer:\nAna peels an orange in 3 minutes, so...","[def solution():\n """"""There are some orange...",[def solution():\n '''\n Create a functi...,[5.0],[5.0],[5.0],[5.0],[False],5,5.0,True,1.0,1.0
1316,Mark's car breaks down and he needs to get a n...,"[Answer:\nThe cost of the radiator is $400, bu...","[def solution():\n """"""Mark's car breaks dow...",[Here is the Python function that solves the p...,[230.0],[470.0],[None],[None],[True],230,None,True,0.0,NaN
1317,"Farmer Brown has 20 animals on his farm, all e...",[Answer:\nLet's say the number of chickens is ...,"[def solution():\n """"""Farmer Brown has 20 a...",[def solution():\n '''\n Create a functi...,[5.0],[None],[40.0],[None],[True],5,40.0,True,NaN,0.0
1318,Henry and 3 of his friends order 7 pizzas for ...,"[Answer:\nThere are 7 pizzas, and each pizza i...","[def solution():\n """"""Henry and 3 of his fr...",[def solution():\n '''\n Create a functi...,[14.0],[14.0],[14.0],[14.0],[False],14,14.0,True,1.0,1.0

In [5]:
# [] in df.majvote_answers.value_counts().index.tolist()
df.need_selection.apply(lambda lst: lst[0]).value_counts()

need_selection
False    1081
True      238
Name: count, dtype: int64

In [6]:
(df.majvote_answers.apply(lambda lst: lst[0] is None) == df.need_selection.apply(lambda lst: lst[0])).all()

True

In [14]:
# df.p2c_preds = df.p2c_preds.apply(lambda lst: lst[0])
df.loc[:20, ["submission", "p2c_preds", "answer"]]

            submission           p2c_preds  answer
0                 18.0                18.0      18
1                  4.0                 4.0       3
2                 None                None   70000
3                540.0               540.0     540
4                 20.0                20.0      20
5                 None                None      64
6                260.0               260.0     260
7                100.0               100.0     160
8                355.0               355.0      45
9                 None                None     460
10               366.0               366.0     366
11               694.0               694.0     694
12                None                None      13
13                None                None      18
14                60.0                60.0      60
15                None                None     125
16  (80, 80, 150, 150)  (80, 80, 150, 150)     230
17             72500.0             72500.0   57500
18                 7.0                 7.0       7
19  0.3333333333333333            0.333333       6
20  15.000000000000002                15.0      15

In [10]:
(df.p2c_preds == df.submission).all()

False